### PR TITLE
feat: inner percentage display

### PR DESCRIPTION
**Pull request by dannymy**
Hi there, I've discovered this package and used it for a little project. Though API seemed the most customizable and simple in comparison, I've tried to improve it a bit:
- ability to decide on rendering trail (in my case I've found it redundant and had to override visibility with the style rule). So this change will imply adding one more common prop `showTrail`, which will affect both `Line` and `Circle`,
- adding current percent value inside of the `Circle` shape (which I've also found required in my use-case). So this change will be narrowed down only to` Circle` component. This ability will also carry few additional props - styles for this caption and value formatting function.

Also, this is my first contribution to the OSS, so any comments are more than welcome.
And if this change completely is inconsistent with the current implementation or does not align well with it, feel free to dismiss.

### CODE REVIEW

**Comment by benjycui** [comment]
I am not sure if [`antd.Progress`](https://ant.design/components/progress/#components-progress-demo-circle) can satisfy your use case?

**Comment by dannymy** [comment]
Yes, this is exactly the thing I'm talking, in my project though I've already used react-component/progress with a small workaround to add a caption inside.

**Comment by benjycui** [comment]
So, could you just use antd.Process? We want rc-process to be simple.

**Comment by dannymy** [comment]
Okay, so closing then.

**Pull request closed without merging**
